[keybindings.Global]
"<q>" = "Quit"
"<Ctrl-d>" = "Quit"
"<Ctrl-c>" = "Quit"
"<Tab>" = "CycleFocus"
"<Backtab>" = "CycleFocusBackwards"
"<?>" = "ToggleHelp"
"<Esc>" = "CloseModal"

[keybindings.DeviceList]
"<j>" = "Down"
"<k>" = "Up"
"<Down>" = "Down"
"<Up>" = "Up"
"<x>" = "Disconnect"
"<r>" = "Refresh"
"<e>" = "OpenEmulators"

[keybindings.EmulatorsModal]
"<j>" = "Down"
"<k>" = "Up"
"<Down>" = "Down"
"<Up>" = "Up"
"<x>" = "Kill"
"<Enter>" = "Select"

[keybindings.Content]
